crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud_app.urls')),
]

crud/crud_app/urls.py
from django.urls import path
from crud_app import views

app_name = "crud_app"

urlpatterns = [
    
    path('',views.index, name= "index"),
    path('student_form/',views.student_form, name= "student_form"),
    path('student_info/<int:student_id>/',views.student_info, name= "student_info"),
    path('student_update/<int:student_id>/',views.student_update, name= "student_update"),
    path('student_delete/<int:student_id>/',views.student_delete, name= "student_delete"),
]

crud/crud_app/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.IntegerField()


    def __str__(self):
        return str(self.pk)+ " "+ self.first_name + " " + self.last_name

crud/crud_app/forms.py
from django import forms
from crud_app import models


class StudentForm(forms.ModelForm):
    class Meta:
        model = models.Student
        fields = "__all__"

crud/crud_app/views.py
from django.shortcuts import render
from crud_app import forms
from crud_app.models import Student

# Create your views here.

def index(request):

    student_list = Student.objects.order_by('first_name')
    diction = {'title': "index", 'student_list': student_list}
    
    return render(request, 'crud_app/index.html', context= diction)


def student_form(request):
    form = forms.StudentForm()

    if request.method == "POST":
        form = forms.StudentForm(request.POST)

        if form.is_valid():
            form.save(commit= True)
            return index(request)

    diction ={'title': student_form, 'student_form': form}
    return render( request, 'crud_app/student_form.html', context= diction)


def student_info(request,student_id):
    student_info = Student.objects.get(pk=student_id)
    diction = {'student_info': student_info}
    return render( request, 'crud_app/student_info.html', context= diction)

        
def student_update(request,student_id):
    student_update = Student.objects.get(pk=student_id)
   
    form = forms.StudentForm(instance=student_update)


    if request.method=='POST':
        form= forms.StudentForm(request.POST, instance=student_update)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction= {'student_form':form}        
    return render(request,'crud_app/student_update.html', context= diction)


def student_delete(request,student_id):
    student = Student.objects.get(pk=student_id).delete()
    diction = {'delete_message': "Delete Done"}
    return render( request, 'crud_app/student_delete.html', context= diction)

crud/templates/crud_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body>
    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'crud_app:index' %}"> Index</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'crud_app:student_form' %}">Student Form </a>
        </li>
        
      </ul>

    {% block body %}

    {% endblock %}
    
</body>
</html>

crud/templates/crud_app/index.html
{% extends 'crud_app/base.html' %}

{% block body %}

<h1> Student List </h1>
<ul>
{% if student_list %}

{% for student in student_list %}
<li><a href="{% url 'crud_app:student_info' student_id=student.id %}"> {{student.first_name}} {{student.last_name}} </a></li>

{% endfor %}

{% else %}

<h3> No student</h3>

{% endif %}
</ul>

{% endblock %}

crud/templates/crud_app/student_delete.html
{% extends 'crud_app/base.html' %}

{% block body %}

<div class="alert alert-danger">{{delete_message}}</div>
{% endblock %}

crud/templates/crud_app/student_form.html
{% extends 'crud_app/base.html' %}

{% block body %}

<h1> Student form </h1>

<form action="" method="POST">

    {{ student_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Add Student">
</form>

{% endblock %}

crud/templates/crud_app/student_info.html
{% extends 'crud_app/base.html' %}

{% block body %}

<h1> Student Info </h1>
<h3> Student ID: {{student_info.id}}</h3>
<h3> Student Name: {{student_info.first_name}}{{student_info.last_name}}</h3>
<h3> email: {{student_info.email}}</h3>
<h3> Phone: {{student_info.phone}}</h3>

<a href="{% url 'crud_app:student_update' student_id=student_info.id %}" class="btn btn-primary" >Update</a>

<a href="{% url 'crud_app:student_delete' student_id=student_info.id %}" class="btn btn-primary" >Delete</a>

{% endblock %}

crud/templates/crud_app/student_update.html
{% extends 'crud_app/base.html' %}

{% block body %}

<h> student Update</h>


<form action="" method="POST">
    {{student_form.as_p}}
    {% csrf_token %}

    <input type="submit" value="update">

</form>
{% endblock %}